
# .dP"Y8 88""Yb 8b    d8       .d 
# `Ybo." 88__dP 88b  d88     .d88 
# o.`Y8b 88""Yb 88YbdP88       88 
# 8bodP' 88oodP 88 YY 88       88 


sbm3x3_bigclam:
    clamiter_init:
        dim_feat: 2
        s_reg: 0.0
        l1_reg: 0.01
    feat_opt:
        lr: 0.00001
        n_iter: 4000

sbm3x3_iegam:
    clamiter_init:
        dim_feat: 4
        s_reg: 0.0
        l1_reg: 0.05
    feat_opt:
        lr: 0.00001
        n_iter: 4000

sbm3x3_pclam:
    clamiter_init:
        dim_feat: 2
        l1_reg: 0.1
        s_reg: 0.0
        prior: None
        hidden_dim: 128
        num_coupling_blocks: 32
        num_layers_mlp: 2
    feat_opt:
        n_iter: 1000
        lr: 0.00001
    prior_opt:
        n_iter: 2500
        lr: 0.000001
        noise_amp: 0.1
        weight_decay: 0.01
    back_forth:
        n_back_forth: 15
        scheduler_step_size: 300
        scheduler_gamma: 0.1
        first_func_in_fit: 'fit_prior'
        early_stop_fit: 0

sbm3x3_piegam:
    clamiter_init:
        dim_feat: 4
        l1_reg: 0.0
        s_reg: 0.0
        prior: None
        hidden_dim: 64
        num_coupling_blocks: 32 
        num_layers_mlp: 2
    feat_opt:
        n_iter: 2000
        lr: 0.00001
    prior_opt:
        n_iter: 2000
        lr: 0.000005
        noise_amp: 0.1
        weight_decay: 0.01
    back_forth:
        n_back_forth: 15
        scheduler_step_size: 100
        scheduler_gamma: 0.5
        first_func_in_fit: 'fit_prior'
        early_stop_fit: 0


# 88  88    db    88     888888      dP""b8 888888 88b 88 888888 888888 88""Yb 
# 88  88   dPYb   88     88__       dP   `" 88__   88Yb88   88   88__   88__dP 
# 888888  dP__Yb  88  .o 88""       Yb      88""   88 Y88   88   88""   88"Yb  
# 88  88 dP""""Yb 88ood8 88          YboodP 888888 88  Y8   88   888888 88  Yb 


sbm3x3HalfCenter_bigclam:
    clamiter_init:
        dim_feat: 2
        s_reg: 0.0
        l1_reg: 0.01
    feat_opt:
        lr: 0.00001
        n_iter: 10000

sbm3x3HalfCenter_iegam:
    clamiter_init:
        dim_feat: 4
        s_reg: 0.0
        l1_reg: 0.05
    feat_opt:
        lr: 0.00001
        n_iter: 10000

sbm3x3HalfCenter_pclam:
    clamiter_init:
        dim_feat: 2
        l1_reg: 0.1
        s_reg: 0.0
        prior: None
        hidden_dim: 64
        num_coupling_blocks: 32
        num_layers_mlp: 2
    feat_opt:
        n_iter: 1000
        lr: 0.00001
    prior_opt:
        n_iter: 2500
        lr: 0.000001
        noise_amp: 0.1
        weight_decay: 0.01
    back_forth:
        n_back_forth: 15
        scheduler_step_size: 300
        scheduler_gamma: 0.1
        first_func_in_fit: 'fit_prior'
        early_stop_fit: 0

sbm3x3HalfCenter_piegam:
    clamiter_init:
        dim_feat: 4
        l1_reg: 0.0
        s_reg: 0.0
        prior: None
        hidden_dim: 64
        num_coupling_blocks: 32 
        num_layers_mlp: 2
    feat_opt:
        n_iter: 2000
        lr: 0.00001
    prior_opt:
        n_iter: 2000
        lr: 0.000005
        noise_amp: 0.1
        weight_decay: 0.01
    back_forth:
        n_back_forth: 15
        scheduler_step_size: 100
        scheduler_gamma: 0.5
        first_func_in_fit: 'fit_prior'
        early_stop_fit: 0


# 88  88    db    88     888888     8888b.  88    db     dP""b8 
# 88  88   dPYb   88     88__        8I  Yb 88   dPYb   dP   `" 
# 888888  dP__Yb  88  .o 88""        8I  dY 88  dP__Yb  Yb  "88 
# 88  88 dP""""Yb 88ood8 88         8888Y"  88 dP""""Yb  YboodP 


sbm3x3HalfDiag_bigclam:
    clamiter_init:
        dim_feat: 2
        s_reg: 0.0
        l1_reg: 0.01
    feat_opt:
        lr: 0.00001
        n_iter: 10000

sbm3x3HalfDiag_iegam:
    clamiter_init:
        dim_feat: 4
        s_reg: 0.0
        l1_reg: 0.05
    feat_opt:
        lr: 0.00001
        n_iter: 10000

sbm3x3HalfDiag_pclam:
    clamiter_init:
        dim_feat: 2
        l1_reg: 0.1
        s_reg: 0.0
        prior: None
        hidden_dim: 128
        num_coupling_blocks: 32
        num_layers_mlp: 2
    feat_opt:
        n_iter: 1000
        lr: 0.00001
    prior_opt:
        n_iter: 2500
        lr: 0.000001
        noise_amp: 0.1
        weight_decay: 0.01
    back_forth:
        n_back_forth: 20
        scheduler_step_size: 300
        scheduler_gamma: 0.1
        first_func_in_fit: 'fit_prior'
        early_stop_fit: 0

sbm3x3HalfDiag_piegam:
    clamiter_init:
        dim_feat: 4
        l1_reg: 0.0
        s_reg: 0.0
        prior: None
        hidden_dim: 64
        num_coupling_blocks: 32 
        num_layers_mlp: 2
    feat_opt:
        n_iter: 2000
        lr: 0.00001
    prior_opt:
        n_iter: 2000
        lr: 0.000005
        noise_amp: 0.1
        weight_decay: 0.01
    back_forth:
        n_back_forth: 20
        scheduler_step_size: 100
        scheduler_gamma: 0.5
        first_func_in_fit: 'fit_prior'
        early_stop_fit: 0



# 8b    d8  dP"Yb   dP"Yb  88b 88 .dP"Y8 
# 88b  d88 dP   Yb dP   Yb 88Yb88 `Ybo." 
# 88YbdP88 Yb   dP Yb   dP 88 Y88 o.`Y8b 
# 88 YY 88  YbodP   YbodP  88  Y8 8bodP' 

TwoMoons_bigclam:
    clamiter_init:
        dim_feat: 2
        s_reg: 0.0
        l1_reg: 0.01

    feat_opt:
        lr: 0.00001
        n_iter: 10000

TwoMoons_iegam:
    clamiter_init:
        dim_feat: 2
        s_reg: 0.0
        l1_reg: 0.05
    feat_opt:
        lr: 0.00001
        n_iter: 10000

TwoMoons_pclam:
    clamiter_init:
        dim_feat: 2
        l1_reg: 0.1
        s_reg: 0.0
        prior: None
        hidden_dim: 128
        num_coupling_blocks: 32
        num_layers_mlp: 2
    feat_opt:
        n_iter: 500
        lr: 0.00001
    prior_opt:
        n_iter: 1300
        lr: 0.0000001
        noise_amp: 0.1
        weight_decay: 0.01
    back_forth:
        n_back_forth: 20
        scheduler_step_size: 300
        scheduler_gamma: 0.1
        first_func_in_fit: 'fit_prior'
        early_stop_fit: 0

TwoMoons_piegam:
    clamiter_init:
        dim_feat: 4
        l1_reg: 0.0
        s_reg: 0.0
        prior: None
        hidden_dim: 64
        num_coupling_blocks: 32 
        num_layers_mlp: 2
    feat_opt:
        n_iter: 2000
        lr: 0.00001
    prior_opt:
        n_iter: 2000
        lr: 0.000005
        noise_amp: 0.01
        weight_decay: 0.01
    back_forth:
        n_back_forth: 30
        scheduler_step_size: 100
        scheduler_gamma: 0.5
        first_func_in_fit: 'fit_prior'
        early_stop_fit: 0


#  dP""b8 88 88""Yb  dP""b8 
# dP   `" 88 88__dP dP   `" 
# Yb      88 88"Yb  Yb      
#  YboodP 88 88  Yb  YboodP 

Circ_bigclam:
    clamiter_init:
        dim_feat: 2
        s_reg: 0.0
        l1_reg: 0.01
    feat_opt:
        lr: 0.00001
        n_iter: 10000

Circ_iegam:
    clamiter_init:
        dim_feat: 4
        s_reg: 0.0
        l1_reg: 0.05
    feat_opt:
        lr: 0.00001
        n_iter: 10000

Circ_pclam:
    clamiter_init:
        dim_feat: 2
        l1_reg: 0.1
        s_reg: 0.0
        prior: None
        hidden_dim: 128
        num_coupling_blocks: 32
        num_layers_mlp: 2
    feat_opt:
        n_iter: 1000
        lr: 0.00001
    prior_opt:
        n_iter: 1300
        lr: 0.000001
        noise_amp: 0.1
        weight_decay: 0.01
    back_forth:
        n_back_forth: 30
        scheduler_step_size: 100
        scheduler_gamma: 0.5
        first_func_in_fit: 'fit_prior'
        early_stop_fit: 0

Circ_piegam:
    clamiter_init:
        dim_feat: 4
        l1_reg: 0.0
        s_reg: 0.0
        prior: None
        hidden_dim: 64
        num_coupling_blocks: 32 
        num_layers_mlp: 2
    feat_opt:
        n_iter: 2000
        lr: 0.00001
    prior_opt:
        n_iter: 2000
        lr: 0.000005
        noise_amp: 0.01
        weight_decay: 0.01
    back_forth:
        n_back_forth: 30
        scheduler_step_size: 100
        scheduler_gamma: 0.5
        first_func_in_fit: 'fit_prior'
        early_stop_fit: 0


#  dP""b8 88  88 88   88 88""Yb      dP""b8    db    88   88 .dP"Y8 
# dP   `" 88  88 88   88 88__dP     dP   `"   dPYb   88   88 `Ybo." 
# Yb      888888 Y8   8P 88""Yb     Yb  "88  dP__Yb  Y8   8P o.`Y8b 
#  YboodP 88  88 `YbodP' 88oodP      YboodP dP""""Yb `YbodP' 8bodP' 

ChubGaus_bigclam:
    clamiter_init:
        dim_feat: 2
        s_reg: 0.0
        l1_reg: 0.01
    feat_opt:
        lr: 0.00001
        n_iter: 40000

ChubGaus_iegam:
    clamiter_init:
        dim_feat: 4
        s_reg: 0.0
        l1_reg: 0.05
    feat_opt:
        lr: 0.00001
        n_iter: 40000

ChubGaus_pclam:
    clamiter_init:
        dim_feat: 2
        l1_reg: 0.1
        s_reg: 0.0
        prior: None
        hidden_dim: 128
        num_coupling_blocks: 32
        num_layers_mlp: 2
    feat_opt:
        n_iter: 1000
        lr: 0.00001
    prior_opt:
        n_iter: 2500
        lr: 0.000001
        noise_amp: 0.1
        weight_decay: 0.01
    back_forth:
        n_back_forth: 60
        scheduler_step_size: 300
        scheduler_gamma: 0.1
        first_func_in_fit: 'fit_prior'
        early_stop_fit: 0

ChubGaus_piegam:
    clamiter_init:
        dim_feat: 4
        l1_reg: 0.0
        s_reg: 0.0
        prior: None
        hidden_dim: 64
        num_coupling_blocks: 32 
        num_layers_mlp: 2
    feat_opt:
        n_iter: 2000
        lr: 0.00001
    prior_opt:
        n_iter: 2000
        lr: 0.000005
        noise_amp: 0.1
        weight_decay: 0.01
    back_forth:
        n_back_forth: 30
        scheduler_step_size: 100
        scheduler_gamma: 0.5
        first_func_in_fit: 'fit_prior'
        early_stop_fit: 0



#  dP""b8 88      dP"Yb  88""Yb    db    88     
# dP   `" 88     dP   Yb 88__dP   dPYb   88     
# Yb  "88 88  .o Yb   dP 88""Yb  dP__Yb  88  .o 
#  YboodP 88ood8  YbodP  88oodP dP""""Yb 88ood8 

# global config

MightyConfigs_iegam:
    clamiter_init: 
        dim_feat: 30
        dim_attr: 64
        s_reg: 0.0
        l1_reg: 1
        T: 1
        hidden_dim: 64
        num_coupling_blocks: 32
        num_layers_mlp: 2
    feat_opt: 
        lr: 0.000001
        n_iter: 2000
        early_stop: 0
    

MightyConfigs_piegam:
    clamiter_init: 
        dim_feat: 30
        dim_attr: 100
        s_reg: 0.0
        l1_reg: 1
        T: 1
        hidden_dim: 64
        num_coupling_blocks: 32
        num_layers_mlp: 2
    feat_opt: 
        lr: 0.000001
        n_iter: 2000
        early_stop: 0
    prior_opt:
        n_iter: 1000
        lr: 0.0000001
        noise_amp: 0.005
        weight_decay: 0.1
        early_stop: 0
    back_forth:
        n_back_forth: 15
        scheduler_step_size: 10
        scheduler_gamma: 0.5
        early_stop_fit: 0
        first_func_in_fit: "fit_feats"


MightyConfigs_bigclam:
    clamiter_init: 
        dim_feat: 24
        dim_attr: 100
        s_reg: 0.0
        l1_reg: 1
        T: 1
        hidden_dim: 64
        num_coupling_blocks: 32
        num_layers_mlp: 2
    feat_opt: 
        lr: 0.000001
        n_iter: 200
        early_stop: 0


MightyConfigs_pclam:
    clamiter_init: 
        dim_feat: 24
        dim_attr: 100
        s_reg: 0.0
        l1_reg: 1
        T: 1
        hidden_dim: 64
        num_coupling_blocks: 32
        num_layers_mlp: 2
    feat_opt: 
        lr: 0.000001
        n_iter: 200
        early_stop: 0
    prior_opt:
        n_iter: 1000
        lr: 0.0000001
        noise_amp: 0.01
        weight_decay: 0.1
        early_stop: 0
    back_forth:
        n_back_forth: 10
        scheduler_step_size: 6
        scheduler_gamma: 0.5
        early_stop_fit: 0
        first_func_in_fit: "fit_feats"
